# Generated by Django 3.1.2 on 2020-10-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=200)),
                ('confirmarClave', models.CharField(max_length=200)),
                ('tipoEmpresa', models.CharField(blank=True, choices=[(1, 'Gastronomica'), (2, 'Salud'), (3, 'Logistica')], default=0, help_text='Tipo de empresa', max_length=100)),
            ],
        ),
    ]
