# Generated by Django 3.1.2 on 2020-11-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='tipoEmpresa',
            field=models.CharField(blank=True, choices=[('1', 'Gastronomica'), ('2', 'Salud'), ('3', 'Logistica')], default=0, help_text='Tipo de empresa', max_length=1),
        ),
        migrations.CreateModel(
            name='transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.local')),
            ],
        ),
    ]
